// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAplJKW1ifTfWp6nKoRT6YnvI5M43I1Jf8',
    appId: '1:603635278520:web:cf713ff3b39abe6fc0ca4d',
    messagingSenderId: '603635278520',
    projectId: 'cs-flutter',
    authDomain: 'cs-flutter.firebaseapp.com',
    storageBucket: 'cs-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4KtCvKZWfkijpyPMdc44cFZzwsa_6Q1M',
    appId: '1:603635278520:android:d4780dd85bf65183c0ca4d',
    messagingSenderId: '603635278520',
    projectId: 'cs-flutter',
    storageBucket: 'cs-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzjvfrMhnyqIGuhtmkYpTVhdxSq_JPyj0',
    appId: '1:603635278520:ios:a4f8ee1595990702c0ca4d',
    messagingSenderId: '603635278520',
    projectId: 'cs-flutter',
    storageBucket: 'cs-flutter.appspot.com',
    androidClientId: '603635278520-4nfqspmd6jfgkqm97p28m0mtes4ncsvh.apps.googleusercontent.com',
    iosClientId: '603635278520-jt69tvg3du99jtoe2r8h5sl20hia2ocm.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzjvfrMhnyqIGuhtmkYpTVhdxSq_JPyj0',
    appId: '1:603635278520:ios:61f7940332e4edc5c0ca4d',
    messagingSenderId: '603635278520',
    projectId: 'cs-flutter',
    storageBucket: 'cs-flutter.appspot.com',
    androidClientId: '603635278520-4nfqspmd6jfgkqm97p28m0mtes4ncsvh.apps.googleusercontent.com',
    iosClientId: '603635278520-jmfje3517vl34brjsb0t50bgjn3nga2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduler.RunnerTests',
  );
}
